/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.Dashboard;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DashboardRecord extends UpdatableRecordImpl<DashboardRecord> implements Record8<String, String, String, Short, Short, Short, Short, Boolean> {

    private static final long serialVersionUID = -1089950416;

    /**
     * Setter for <code>public.dashboard.channel_id</code>.
     */
    public void setChannelId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dashboard.channel_id</code>.
     */
    public String getChannelId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.dashboard.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dashboard.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.dashboard.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.dashboard.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.dashboard.x</code>.
     */
    public void setX(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.dashboard.x</code>.
     */
    public Short getX() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.dashboard.y</code>.
     */
    public void setY(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.dashboard.y</code>.
     */
    public Short getY() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.dashboard.width</code>.
     */
    public void setWidth(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.dashboard.width</code>.
     */
    public Short getWidth() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.dashboard.height</code>.
     */
    public void setHeight(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.dashboard.height</code>.
     */
    public Short getHeight() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.dashboard.show</code>.
     */
    public void setShow(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.dashboard.show</code>.
     */
    public Boolean getShow() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, Short, Short, Short, Short, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, String, Short, Short, Short, Short, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Dashboard.DASHBOARD.CHANNEL_ID;
    }

    @Override
    public Field<String> field2() {
        return Dashboard.DASHBOARD.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Dashboard.DASHBOARD.TYPE;
    }

    @Override
    public Field<Short> field4() {
        return Dashboard.DASHBOARD.X;
    }

    @Override
    public Field<Short> field5() {
        return Dashboard.DASHBOARD.Y;
    }

    @Override
    public Field<Short> field6() {
        return Dashboard.DASHBOARD.WIDTH;
    }

    @Override
    public Field<Short> field7() {
        return Dashboard.DASHBOARD.HEIGHT;
    }

    @Override
    public Field<Boolean> field8() {
        return Dashboard.DASHBOARD.SHOW;
    }

    @Override
    public String component1() {
        return getChannelId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public Short component4() {
        return getX();
    }

    @Override
    public Short component5() {
        return getY();
    }

    @Override
    public Short component6() {
        return getWidth();
    }

    @Override
    public Short component7() {
        return getHeight();
    }

    @Override
    public Boolean component8() {
        return getShow();
    }

    @Override
    public String value1() {
        return getChannelId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public Short value4() {
        return getX();
    }

    @Override
    public Short value5() {
        return getY();
    }

    @Override
    public Short value6() {
        return getWidth();
    }

    @Override
    public Short value7() {
        return getHeight();
    }

    @Override
    public Boolean value8() {
        return getShow();
    }

    @Override
    public DashboardRecord value1(String value) {
        setChannelId(value);
        return this;
    }

    @Override
    public DashboardRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public DashboardRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public DashboardRecord value4(Short value) {
        setX(value);
        return this;
    }

    @Override
    public DashboardRecord value5(Short value) {
        setY(value);
        return this;
    }

    @Override
    public DashboardRecord value6(Short value) {
        setWidth(value);
        return this;
    }

    @Override
    public DashboardRecord value7(Short value) {
        setHeight(value);
        return this;
    }

    @Override
    public DashboardRecord value8(Boolean value) {
        setShow(value);
        return this;
    }

    @Override
    public DashboardRecord values(String value1, String value2, String value3, Short value4, Short value5, Short value6, Short value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardRecord
     */
    public DashboardRecord() {
        super(Dashboard.DASHBOARD);
    }

    /**
     * Create a detached, initialised DashboardRecord
     */
    public DashboardRecord(String channelId, String userId, String type, Short x, Short y, Short width, Short height, Boolean show) {
        super(Dashboard.DASHBOARD);

        set(0, channelId);
        set(1, userId);
        set(2, type);
        set(3, x);
        set(4, y);
        set(5, width);
        set(6, height);
        set(7, show);
    }
}
