/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.DashboardOld;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DashboardOldRecord extends UpdatableRecordImpl<DashboardOldRecord> implements Record7<String, String, Short, Short, Short, Short, Boolean> {

    private static final long serialVersionUID = 1636608616;

    /**
     * Setter for <code>public.dashboard_old.user_id</code>.
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dashboard_old.user_id</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.dashboard_old.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dashboard_old.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.dashboard_old.x</code>.
     */
    public void setX(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.dashboard_old.x</code>.
     */
    public Short getX() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.dashboard_old.y</code>.
     */
    public void setY(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.dashboard_old.y</code>.
     */
    public Short getY() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.dashboard_old.width</code>.
     */
    public void setWidth(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.dashboard_old.width</code>.
     */
    public Short getWidth() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.dashboard_old.height</code>.
     */
    public void setHeight(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.dashboard_old.height</code>.
     */
    public Short getHeight() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.dashboard_old.show</code>.
     */
    public void setShow(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.dashboard_old.show</code>.
     */
    public Boolean getShow() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, Short, Short, Short, Short, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, Short, Short, Short, Short, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DashboardOld.DASHBOARD_OLD.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return DashboardOld.DASHBOARD_OLD.TYPE;
    }

    @Override
    public Field<Short> field3() {
        return DashboardOld.DASHBOARD_OLD.X;
    }

    @Override
    public Field<Short> field4() {
        return DashboardOld.DASHBOARD_OLD.Y;
    }

    @Override
    public Field<Short> field5() {
        return DashboardOld.DASHBOARD_OLD.WIDTH;
    }

    @Override
    public Field<Short> field6() {
        return DashboardOld.DASHBOARD_OLD.HEIGHT;
    }

    @Override
    public Field<Boolean> field7() {
        return DashboardOld.DASHBOARD_OLD.SHOW;
    }

    @Override
    public String component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public Short component3() {
        return getX();
    }

    @Override
    public Short component4() {
        return getY();
    }

    @Override
    public Short component5() {
        return getWidth();
    }

    @Override
    public Short component6() {
        return getHeight();
    }

    @Override
    public Boolean component7() {
        return getShow();
    }

    @Override
    public String value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public Short value3() {
        return getX();
    }

    @Override
    public Short value4() {
        return getY();
    }

    @Override
    public Short value5() {
        return getWidth();
    }

    @Override
    public Short value6() {
        return getHeight();
    }

    @Override
    public Boolean value7() {
        return getShow();
    }

    @Override
    public DashboardOldRecord value1(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public DashboardOldRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public DashboardOldRecord value3(Short value) {
        setX(value);
        return this;
    }

    @Override
    public DashboardOldRecord value4(Short value) {
        setY(value);
        return this;
    }

    @Override
    public DashboardOldRecord value5(Short value) {
        setWidth(value);
        return this;
    }

    @Override
    public DashboardOldRecord value6(Short value) {
        setHeight(value);
        return this;
    }

    @Override
    public DashboardOldRecord value7(Boolean value) {
        setShow(value);
        return this;
    }

    @Override
    public DashboardOldRecord values(String value1, String value2, Short value3, Short value4, Short value5, Short value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardOldRecord
     */
    public DashboardOldRecord() {
        super(DashboardOld.DASHBOARD_OLD);
    }

    /**
     * Create a detached, initialised DashboardOldRecord
     */
    public DashboardOldRecord(String userId, String type, Short x, Short y, Short width, Short height, Boolean show) {
        super(DashboardOld.DASHBOARD_OLD);

        set(0, userId);
        set(1, type);
        set(2, x);
        set(3, y);
        set(4, width);
        set(5, height);
        set(6, show);
    }
}
