/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.Notification;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NotificationRecord extends UpdatableRecordImpl<NotificationRecord> implements Record6<Long, String, String, OffsetDateTime, Boolean, String> {

    private static final long serialVersionUID = -97367012;

    /**
     * Setter for <code>public.notification.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notification.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.notification.channel_id</code>.
     */
    public void setChannelId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notification.channel_id</code>.
     */
    public String getChannelId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.notification.user_id</code>.
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notification.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.notification.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notification.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.notification.hide</code>.
     */
    public void setHide(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notification.hide</code>.
     */
    public Boolean getHide() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.notification.type</code>.
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notification.type</code>.
     */
    public String getType() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, OffsetDateTime, Boolean, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, OffsetDateTime, Boolean, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Notification.NOTIFICATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Notification.NOTIFICATION.CHANNEL_ID;
    }

    @Override
    public Field<String> field3() {
        return Notification.NOTIFICATION.USER_ID;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Notification.NOTIFICATION.CREATED_AT;
    }

    @Override
    public Field<Boolean> field5() {
        return Notification.NOTIFICATION.HIDE;
    }

    @Override
    public Field<String> field6() {
        return Notification.NOTIFICATION.TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getChannelId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Boolean component5() {
        return getHide();
    }

    @Override
    public String component6() {
        return getType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getChannelId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public Boolean value5() {
        return getHide();
    }

    @Override
    public String value6() {
        return getType();
    }

    @Override
    public NotificationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationRecord value2(String value) {
        setChannelId(value);
        return this;
    }

    @Override
    public NotificationRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public NotificationRecord value4(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NotificationRecord value5(Boolean value) {
        setHide(value);
        return this;
    }

    @Override
    public NotificationRecord value6(String value) {
        setType(value);
        return this;
    }

    @Override
    public NotificationRecord values(Long value1, String value2, String value3, OffsetDateTime value4, Boolean value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(Long id, String channelId, String userId, OffsetDateTime createdAt, Boolean hide, String type) {
        super(Notification.NOTIFICATION);

        set(0, id);
        set(1, channelId);
        set(2, userId);
        set(3, createdAt);
        set(4, hide);
        set(5, type);
    }
}
