/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.TwitchSubscriptions;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TwitchSubscriptionsRecord extends UpdatableRecordImpl<TwitchSubscriptionsRecord> implements Record8<Long, String, String, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = -1091654574;

    /**
     * Setter for <code>public.twitch_subscriptions.notification_id</code>.
     */
    public void setNotificationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.notification_id</code>.
     */
    public Long getNotificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.recipient_username</code>.
     */
    public void setRecipientUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.recipient_username</code>.
     */
    public String getRecipientUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.recipient_display_name</code>.
     */
    public void setRecipientDisplayName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.recipient_display_name</code>.
     */
    public String getRecipientDisplayName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.sub_plan</code>.
     */
    public void setSubPlan(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.sub_plan</code>.
     */
    public String getSubPlan() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.cumulative_months</code>.
     */
    public void setCumulativeMonths(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.cumulative_months</code>.
     */
    public Integer getCumulativeMonths() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.streak_months</code>.
     */
    public void setStreakMonths(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.streak_months</code>.
     */
    public Integer getStreakMonths() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.context</code>.
     */
    public void setContext(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.context</code>.
     */
    public String getContext() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.message</code>.
     */
    public void setMessage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.message</code>.
     */
    public String getMessage() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, Integer, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, String, Integer, Integer, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.NOTIFICATION_ID;
    }

    @Override
    public Field<String> field2() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.RECIPIENT_USERNAME;
    }

    @Override
    public Field<String> field3() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.RECIPIENT_DISPLAY_NAME;
    }

    @Override
    public Field<String> field4() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.SUB_PLAN;
    }

    @Override
    public Field<Integer> field5() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.CUMULATIVE_MONTHS;
    }

    @Override
    public Field<Integer> field6() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.STREAK_MONTHS;
    }

    @Override
    public Field<String> field7() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.CONTEXT;
    }

    @Override
    public Field<String> field8() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.MESSAGE;
    }

    @Override
    public Long component1() {
        return getNotificationId();
    }

    @Override
    public String component2() {
        return getRecipientUsername();
    }

    @Override
    public String component3() {
        return getRecipientDisplayName();
    }

    @Override
    public String component4() {
        return getSubPlan();
    }

    @Override
    public Integer component5() {
        return getCumulativeMonths();
    }

    @Override
    public Integer component6() {
        return getStreakMonths();
    }

    @Override
    public String component7() {
        return getContext();
    }

    @Override
    public String component8() {
        return getMessage();
    }

    @Override
    public Long value1() {
        return getNotificationId();
    }

    @Override
    public String value2() {
        return getRecipientUsername();
    }

    @Override
    public String value3() {
        return getRecipientDisplayName();
    }

    @Override
    public String value4() {
        return getSubPlan();
    }

    @Override
    public Integer value5() {
        return getCumulativeMonths();
    }

    @Override
    public Integer value6() {
        return getStreakMonths();
    }

    @Override
    public String value7() {
        return getContext();
    }

    @Override
    public String value8() {
        return getMessage();
    }

    @Override
    public TwitchSubscriptionsRecord value1(Long value) {
        setNotificationId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value2(String value) {
        setRecipientUsername(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value3(String value) {
        setRecipientDisplayName(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value4(String value) {
        setSubPlan(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value5(Integer value) {
        setCumulativeMonths(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value6(Integer value) {
        setStreakMonths(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value7(String value) {
        setContext(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value8(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord values(Long value1, String value2, String value3, String value4, Integer value5, Integer value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitchSubscriptionsRecord
     */
    public TwitchSubscriptionsRecord() {
        super(TwitchSubscriptions.TWITCH_SUBSCRIPTIONS);
    }

    /**
     * Create a detached, initialised TwitchSubscriptionsRecord
     */
    public TwitchSubscriptionsRecord(Long notificationId, String recipientUsername, String recipientDisplayName, String subPlan, Integer cumulativeMonths, Integer streakMonths, String context, String message) {
        super(TwitchSubscriptions.TWITCH_SUBSCRIPTIONS);

        set(0, notificationId);
        set(1, recipientUsername);
        set(2, recipientDisplayName);
        set(3, subPlan);
        set(4, cumulativeMonths);
        set(5, streakMonths);
        set(6, context);
        set(7, message);
    }
}
