/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.TwitchBits;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TwitchBitsRecord extends UpdatableRecordImpl<TwitchBitsRecord> implements Record9<String, Boolean, String, String, String, Integer, Integer, OffsetDateTime, String> {

    private static final long serialVersionUID = -382163792;

    /**
     * Setter for <code>public.twitch_bits.message_id</code>.
     */
    public void setMessageId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.twitch_bits.message_id</code>.
     */
    public String getMessageId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.twitch_bits.anonymous</code>.
     */
    public void setAnonymous(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.twitch_bits.anonymous</code>.
     */
    public Boolean getAnonymous() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.twitch_bits.message</code>.
     */
    public void setMessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.twitch_bits.message</code>.
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.twitch_bits.message_user_id</code>.
     */
    public void setMessageUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.twitch_bits.message_user_id</code>.
     */
    public String getMessageUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.twitch_bits.message_username</code>.
     */
    public void setMessageUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.twitch_bits.message_username</code>.
     */
    public String getMessageUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.twitch_bits.bits_used</code>.
     */
    public void setBitsUsed(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.twitch_bits.bits_used</code>.
     */
    public Integer getBitsUsed() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.twitch_bits.total_bits</code>.
     */
    public void setTotalBits(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.twitch_bits.total_bits</code>.
     */
    public Integer getTotalBits() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.twitch_bits.time</code>.
     */
    public void setTime(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.twitch_bits.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.twitch_bits.channel_id</code>.
     */
    public void setChannelId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.twitch_bits.channel_id</code>.
     */
    public String getChannelId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, Boolean, String, String, String, Integer, Integer, OffsetDateTime, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, Boolean, String, String, String, Integer, Integer, OffsetDateTime, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TwitchBits.TWITCH_BITS.MESSAGE_ID;
    }

    @Override
    public Field<Boolean> field2() {
        return TwitchBits.TWITCH_BITS.ANONYMOUS;
    }

    @Override
    public Field<String> field3() {
        return TwitchBits.TWITCH_BITS.MESSAGE;
    }

    @Override
    public Field<String> field4() {
        return TwitchBits.TWITCH_BITS.MESSAGE_USER_ID;
    }

    @Override
    public Field<String> field5() {
        return TwitchBits.TWITCH_BITS.MESSAGE_USERNAME;
    }

    @Override
    public Field<Integer> field6() {
        return TwitchBits.TWITCH_BITS.BITS_USED;
    }

    @Override
    public Field<Integer> field7() {
        return TwitchBits.TWITCH_BITS.TOTAL_BITS;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return TwitchBits.TWITCH_BITS.TIME;
    }

    @Override
    public Field<String> field9() {
        return TwitchBits.TWITCH_BITS.CHANNEL_ID;
    }

    @Override
    public String component1() {
        return getMessageId();
    }

    @Override
    public Boolean component2() {
        return getAnonymous();
    }

    @Override
    public String component3() {
        return getMessage();
    }

    @Override
    public String component4() {
        return getMessageUserId();
    }

    @Override
    public String component5() {
        return getMessageUsername();
    }

    @Override
    public Integer component6() {
        return getBitsUsed();
    }

    @Override
    public Integer component7() {
        return getTotalBits();
    }

    @Override
    public OffsetDateTime component8() {
        return getTime();
    }

    @Override
    public String component9() {
        return getChannelId();
    }

    @Override
    public String value1() {
        return getMessageId();
    }

    @Override
    public Boolean value2() {
        return getAnonymous();
    }

    @Override
    public String value3() {
        return getMessage();
    }

    @Override
    public String value4() {
        return getMessageUserId();
    }

    @Override
    public String value5() {
        return getMessageUsername();
    }

    @Override
    public Integer value6() {
        return getBitsUsed();
    }

    @Override
    public Integer value7() {
        return getTotalBits();
    }

    @Override
    public OffsetDateTime value8() {
        return getTime();
    }

    @Override
    public String value9() {
        return getChannelId();
    }

    @Override
    public TwitchBitsRecord value1(String value) {
        setMessageId(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value2(Boolean value) {
        setAnonymous(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value3(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value4(String value) {
        setMessageUserId(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value5(String value) {
        setMessageUsername(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value6(Integer value) {
        setBitsUsed(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value7(Integer value) {
        setTotalBits(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value8(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public TwitchBitsRecord value9(String value) {
        setChannelId(value);
        return this;
    }

    @Override
    public TwitchBitsRecord values(String value1, Boolean value2, String value3, String value4, String value5, Integer value6, Integer value7, OffsetDateTime value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitchBitsRecord
     */
    public TwitchBitsRecord() {
        super(TwitchBits.TWITCH_BITS);
    }

    /**
     * Create a detached, initialised TwitchBitsRecord
     */
    public TwitchBitsRecord(String messageId, Boolean anonymous, String message, String messageUserId, String messageUsername, Integer bitsUsed, Integer totalBits, OffsetDateTime time, String channelId) {
        super(TwitchBits.TWITCH_BITS);

        set(0, messageId);
        set(1, anonymous);
        set(2, message);
        set(3, messageUserId);
        set(4, messageUsername);
        set(5, bitsUsed);
        set(6, totalBits);
        set(7, time);
        set(8, channelId);
    }
}
