/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.TwitchFollowers;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwitchFollowersRecord extends UpdatableRecordImpl<TwitchFollowersRecord> implements Record5<String, String, String, Boolean, Timestamp> {

    private static final long serialVersionUID = -829120423;

    /**
     * Setter for <code>public.twitch_followers.channel_id</code>.
     */
    public void setChannelId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.twitch_followers.channel_id</code>.
     */
    public String getChannelId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.twitch_followers.follower_id</code>.
     */
    public void setFollowerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.twitch_followers.follower_id</code>.
     */
    public String getFollowerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.twitch_followers.follower_username</code>.
     */
    public void setFollowerUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.twitch_followers.follower_username</code>.
     */
    public String getFollowerUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.twitch_followers.is_following</code>.
     */
    public void setIsFollowing(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.twitch_followers.is_following</code>.
     */
    public Boolean getIsFollowing() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.twitch_followers.followed_at</code>.
     */
    public void setFollowedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.twitch_followers.followed_at</code>.
     */
    public Timestamp getFollowedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, Timestamp> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Boolean, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Boolean, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TwitchFollowers.TWITCH_FOLLOWERS.CHANNEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TwitchFollowers.TWITCH_FOLLOWERS.FOLLOWER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TwitchFollowers.TWITCH_FOLLOWERS.FOLLOWER_USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TwitchFollowers.TWITCH_FOLLOWERS.IS_FOLLOWING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TwitchFollowers.TWITCH_FOLLOWERS.FOLLOWED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getChannelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFollowerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFollowerUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsFollowing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getFollowedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getChannelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFollowerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFollowerUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsFollowing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFollowedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitchFollowersRecord value1(String value) {
        setChannelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitchFollowersRecord value2(String value) {
        setFollowerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitchFollowersRecord value3(String value) {
        setFollowerUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitchFollowersRecord value4(Boolean value) {
        setIsFollowing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitchFollowersRecord value5(Timestamp value) {
        setFollowedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitchFollowersRecord values(String value1, String value2, String value3, Boolean value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitchFollowersRecord
     */
    public TwitchFollowersRecord() {
        super(TwitchFollowers.TWITCH_FOLLOWERS);
    }

    /**
     * Create a detached, initialised TwitchFollowersRecord
     */
    public TwitchFollowersRecord(String channelId, String followerId, String followerUsername, Boolean isFollowing, Timestamp followedAt) {
        super(TwitchFollowers.TWITCH_FOLLOWERS);

        set(0, channelId);
        set(1, followerId);
        set(2, followerUsername);
        set(3, isFollowing);
        set(4, followedAt);
    }
}
