/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.TwitchSubscriptions;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record3;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwitchSubscriptionsRecord extends UpdatableRecordImpl<TwitchSubscriptionsRecord> implements Record10<String, String, OffsetDateTime, String, String, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1953206618;

    /**
     * Setter for <code>public.twitch_subscriptions.channel_id</code>.
     */
    public void setChannelId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.channel_id</code>.
     */
    public String getChannelId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.recipient_id</code>.
     */
    public void setRecipientId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.recipient_id</code>.
     */
    public String getRecipientId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.time</code>.
     */
    public void setTime(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.recipient_username</code>.
     */
    public void setRecipientUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.recipient_username</code>.
     */
    public String getRecipientUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.recipient_display_name</code>.
     */
    public void setRecipientDisplayName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.recipient_display_name</code>.
     */
    public String getRecipientDisplayName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.sub_plan</code>.
     */
    public void setSubPlan(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.sub_plan</code>.
     */
    public String getSubPlan() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.cumulative_months</code>.
     */
    public void setCumulativeMonths(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.cumulative_months</code>.
     */
    public Integer getCumulativeMonths() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.streak_months</code>.
     */
    public void setStreakMonths(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.streak_months</code>.
     */
    public Integer getStreakMonths() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.context</code>.
     */
    public void setContext(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.context</code>.
     */
    public String getContext() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.twitch_subscriptions.message</code>.
     */
    public void setMessage(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions.message</code>.
     */
    public String getMessage() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, OffsetDateTime> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, OffsetDateTime, String, String, String, Integer, Integer, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, OffsetDateTime, String, String, String, Integer, Integer, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.CHANNEL_ID;
    }

    @Override
    public Field<String> field2() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.RECIPIENT_ID;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.TIME;
    }

    @Override
    public Field<String> field4() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.RECIPIENT_USERNAME;
    }

    @Override
    public Field<String> field5() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.RECIPIENT_DISPLAY_NAME;
    }

    @Override
    public Field<String> field6() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.SUB_PLAN;
    }

    @Override
    public Field<Integer> field7() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.CUMULATIVE_MONTHS;
    }

    @Override
    public Field<Integer> field8() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.STREAK_MONTHS;
    }

    @Override
    public Field<String> field9() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.CONTEXT;
    }

    @Override
    public Field<String> field10() {
        return TwitchSubscriptions.TWITCH_SUBSCRIPTIONS.MESSAGE;
    }

    @Override
    public String component1() {
        return getChannelId();
    }

    @Override
    public String component2() {
        return getRecipientId();
    }

    @Override
    public OffsetDateTime component3() {
        return getTime();
    }

    @Override
    public String component4() {
        return getRecipientUsername();
    }

    @Override
    public String component5() {
        return getRecipientDisplayName();
    }

    @Override
    public String component6() {
        return getSubPlan();
    }

    @Override
    public Integer component7() {
        return getCumulativeMonths();
    }

    @Override
    public Integer component8() {
        return getStreakMonths();
    }

    @Override
    public String component9() {
        return getContext();
    }

    @Override
    public String component10() {
        return getMessage();
    }

    @Override
    public String value1() {
        return getChannelId();
    }

    @Override
    public String value2() {
        return getRecipientId();
    }

    @Override
    public OffsetDateTime value3() {
        return getTime();
    }

    @Override
    public String value4() {
        return getRecipientUsername();
    }

    @Override
    public String value5() {
        return getRecipientDisplayName();
    }

    @Override
    public String value6() {
        return getSubPlan();
    }

    @Override
    public Integer value7() {
        return getCumulativeMonths();
    }

    @Override
    public Integer value8() {
        return getStreakMonths();
    }

    @Override
    public String value9() {
        return getContext();
    }

    @Override
    public String value10() {
        return getMessage();
    }

    @Override
    public TwitchSubscriptionsRecord value1(String value) {
        setChannelId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value2(String value) {
        setRecipientId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value3(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value4(String value) {
        setRecipientUsername(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value5(String value) {
        setRecipientDisplayName(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value6(String value) {
        setSubPlan(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value7(Integer value) {
        setCumulativeMonths(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value8(Integer value) {
        setStreakMonths(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value9(String value) {
        setContext(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord value10(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsRecord values(String value1, String value2, OffsetDateTime value3, String value4, String value5, String value6, Integer value7, Integer value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitchSubscriptionsRecord
     */
    public TwitchSubscriptionsRecord() {
        super(TwitchSubscriptions.TWITCH_SUBSCRIPTIONS);
    }

    /**
     * Create a detached, initialised TwitchSubscriptionsRecord
     */
    public TwitchSubscriptionsRecord(String channelId, String recipientId, OffsetDateTime time, String recipientUsername, String recipientDisplayName, String subPlan, Integer cumulativeMonths, Integer streakMonths, String context, String message) {
        super(TwitchSubscriptions.TWITCH_SUBSCRIPTIONS);

        set(0, channelId);
        set(1, recipientId);
        set(2, time);
        set(3, recipientUsername);
        set(4, recipientDisplayName);
        set(5, subPlan);
        set(6, cumulativeMonths);
        set(7, streakMonths);
        set(8, context);
        set(9, message);
    }
}
