/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.TwitchSubscriptionsGift;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TwitchSubscriptionsGiftRecord extends UpdatableRecordImpl<TwitchSubscriptionsGiftRecord> implements Record7<Long, String, String, Boolean, String, String, String> {

    private static final long serialVersionUID = 1972358318;

    /**
     * Setter for <code>public.twitch_subscriptions_gift.notification_id</code>.
     */
    public void setNotificationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.notification_id</code>.
     */
    public Long getNotificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.recipient_username</code>.
     */
    public void setRecipientUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.recipient_username</code>.
     */
    public String getRecipientUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.sub_plan</code>.
     */
    public void setSubPlan(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.sub_plan</code>.
     */
    public String getSubPlan() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.anonymous</code>.
     */
    public void setAnonymous(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.anonymous</code>.
     */
    public Boolean getAnonymous() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.gifter_id</code>.
     */
    public void setGifterId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.gifter_id</code>.
     */
    public String getGifterId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.gifter_username</code>.
     */
    public void setGifterUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.gifter_username</code>.
     */
    public String getGifterUsername() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.gifter_display_name</code>.
     */
    public void setGifterDisplayName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.gifter_display_name</code>.
     */
    public String getGifterDisplayName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, Boolean, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, Boolean, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.NOTIFICATION_ID;
    }

    @Override
    public Field<String> field2() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.RECIPIENT_USERNAME;
    }

    @Override
    public Field<String> field3() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.SUB_PLAN;
    }

    @Override
    public Field<Boolean> field4() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.ANONYMOUS;
    }

    @Override
    public Field<String> field5() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.GIFTER_ID;
    }

    @Override
    public Field<String> field6() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.GIFTER_USERNAME;
    }

    @Override
    public Field<String> field7() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.GIFTER_DISPLAY_NAME;
    }

    @Override
    public Long component1() {
        return getNotificationId();
    }

    @Override
    public String component2() {
        return getRecipientUsername();
    }

    @Override
    public String component3() {
        return getSubPlan();
    }

    @Override
    public Boolean component4() {
        return getAnonymous();
    }

    @Override
    public String component5() {
        return getGifterId();
    }

    @Override
    public String component6() {
        return getGifterUsername();
    }

    @Override
    public String component7() {
        return getGifterDisplayName();
    }

    @Override
    public Long value1() {
        return getNotificationId();
    }

    @Override
    public String value2() {
        return getRecipientUsername();
    }

    @Override
    public String value3() {
        return getSubPlan();
    }

    @Override
    public Boolean value4() {
        return getAnonymous();
    }

    @Override
    public String value5() {
        return getGifterId();
    }

    @Override
    public String value6() {
        return getGifterUsername();
    }

    @Override
    public String value7() {
        return getGifterDisplayName();
    }

    @Override
    public TwitchSubscriptionsGiftRecord value1(Long value) {
        setNotificationId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value2(String value) {
        setRecipientUsername(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value3(String value) {
        setSubPlan(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value4(Boolean value) {
        setAnonymous(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value5(String value) {
        setGifterId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value6(String value) {
        setGifterUsername(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value7(String value) {
        setGifterDisplayName(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord values(Long value1, String value2, String value3, Boolean value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitchSubscriptionsGiftRecord
     */
    public TwitchSubscriptionsGiftRecord() {
        super(TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT);
    }

    /**
     * Create a detached, initialised TwitchSubscriptionsGiftRecord
     */
    public TwitchSubscriptionsGiftRecord(Long notificationId, String recipientUsername, String subPlan, Boolean anonymous, String gifterId, String gifterUsername, String gifterDisplayName) {
        super(TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT);

        set(0, notificationId);
        set(1, recipientUsername);
        set(2, subPlan);
        set(3, anonymous);
        set(4, gifterId);
        set(5, gifterUsername);
        set(6, gifterDisplayName);
    }
}
