/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.TwitchSubscriptionsGift;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwitchSubscriptionsGiftRecord extends UpdatableRecordImpl<TwitchSubscriptionsGiftRecord> implements Record9<String, String, OffsetDateTime, String, String, Boolean, String, String, String> {

    private static final long serialVersionUID = 258685763;

    /**
     * Setter for <code>public.twitch_subscriptions_gift.channel_id</code>.
     */
    public void setChannelId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.channel_id</code>.
     */
    public String getChannelId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.recipient_id</code>.
     */
    public void setRecipientId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.recipient_id</code>.
     */
    public String getRecipientId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.time</code>.
     */
    public void setTime(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.recipient_username</code>.
     */
    public void setRecipientUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.recipient_username</code>.
     */
    public String getRecipientUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.sub_plan</code>.
     */
    public void setSubPlan(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.sub_plan</code>.
     */
    public String getSubPlan() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.anonymous</code>.
     */
    public void setAnonymous(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.anonymous</code>.
     */
    public Boolean getAnonymous() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.gifter_id</code>.
     */
    public void setGifterId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.gifter_id</code>.
     */
    public String getGifterId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.gifter_username</code>.
     */
    public void setGifterUsername(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.gifter_username</code>.
     */
    public String getGifterUsername() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.twitch_subscriptions_gift.gifter_display_name</code>.
     */
    public void setGifterDisplayName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.twitch_subscriptions_gift.gifter_display_name</code>.
     */
    public String getGifterDisplayName() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, OffsetDateTime> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, OffsetDateTime, String, String, Boolean, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, OffsetDateTime, String, String, Boolean, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.CHANNEL_ID;
    }

    @Override
    public Field<String> field2() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.RECIPIENT_ID;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.TIME;
    }

    @Override
    public Field<String> field4() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.RECIPIENT_USERNAME;
    }

    @Override
    public Field<String> field5() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.SUB_PLAN;
    }

    @Override
    public Field<Boolean> field6() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.ANONYMOUS;
    }

    @Override
    public Field<String> field7() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.GIFTER_ID;
    }

    @Override
    public Field<String> field8() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.GIFTER_USERNAME;
    }

    @Override
    public Field<String> field9() {
        return TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT.GIFTER_DISPLAY_NAME;
    }

    @Override
    public String component1() {
        return getChannelId();
    }

    @Override
    public String component2() {
        return getRecipientId();
    }

    @Override
    public OffsetDateTime component3() {
        return getTime();
    }

    @Override
    public String component4() {
        return getRecipientUsername();
    }

    @Override
    public String component5() {
        return getSubPlan();
    }

    @Override
    public Boolean component6() {
        return getAnonymous();
    }

    @Override
    public String component7() {
        return getGifterId();
    }

    @Override
    public String component8() {
        return getGifterUsername();
    }

    @Override
    public String component9() {
        return getGifterDisplayName();
    }

    @Override
    public String value1() {
        return getChannelId();
    }

    @Override
    public String value2() {
        return getRecipientId();
    }

    @Override
    public OffsetDateTime value3() {
        return getTime();
    }

    @Override
    public String value4() {
        return getRecipientUsername();
    }

    @Override
    public String value5() {
        return getSubPlan();
    }

    @Override
    public Boolean value6() {
        return getAnonymous();
    }

    @Override
    public String value7() {
        return getGifterId();
    }

    @Override
    public String value8() {
        return getGifterUsername();
    }

    @Override
    public String value9() {
        return getGifterDisplayName();
    }

    @Override
    public TwitchSubscriptionsGiftRecord value1(String value) {
        setChannelId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value2(String value) {
        setRecipientId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value3(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value4(String value) {
        setRecipientUsername(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value5(String value) {
        setSubPlan(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value6(Boolean value) {
        setAnonymous(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value7(String value) {
        setGifterId(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value8(String value) {
        setGifterUsername(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord value9(String value) {
        setGifterDisplayName(value);
        return this;
    }

    @Override
    public TwitchSubscriptionsGiftRecord values(String value1, String value2, OffsetDateTime value3, String value4, String value5, Boolean value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitchSubscriptionsGiftRecord
     */
    public TwitchSubscriptionsGiftRecord() {
        super(TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT);
    }

    /**
     * Create a detached, initialised TwitchSubscriptionsGiftRecord
     */
    public TwitchSubscriptionsGiftRecord(String channelId, String recipientId, OffsetDateTime time, String recipientUsername, String subPlan, Boolean anonymous, String gifterId, String gifterUsername, String gifterDisplayName) {
        super(TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT);

        set(0, channelId);
        set(1, recipientId);
        set(2, time);
        set(3, recipientUsername);
        set(4, subPlan);
        set(5, anonymous);
        set(6, gifterId);
        set(7, gifterUsername);
        set(8, gifterDisplayName);
    }
}
