/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.UserAccessToken;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccessTokenRecord extends UpdatableRecordImpl<UserAccessTokenRecord> implements Record4<String, String, String, Timestamp> {

    private static final long serialVersionUID = 1535598237;

    /**
     * Setter for <code>public.user_access_token.user_id</code>.
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_access_token.user_id</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_access_token.access_token</code>.
     */
    public void setAccessToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_access_token.access_token</code>.
     */
    public String getAccessToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_access_token.refresh_token</code>.
     */
    public void setRefreshToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_access_token.refresh_token</code>.
     */
    public String getRefreshToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_access_token.expired_at</code>.
     */
    public void setExpiredAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_access_token.expired_at</code>.
     */
    public Timestamp getExpiredAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserAccessToken.USER_ACCESS_TOKEN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserAccessToken.USER_ACCESS_TOKEN.ACCESS_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserAccessToken.USER_ACCESS_TOKEN.REFRESH_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return UserAccessToken.USER_ACCESS_TOKEN.EXPIRED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getExpiredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getExpiredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessTokenRecord value1(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessTokenRecord value2(String value) {
        setAccessToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessTokenRecord value3(String value) {
        setRefreshToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessTokenRecord value4(Timestamp value) {
        setExpiredAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessTokenRecord values(String value1, String value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccessTokenRecord
     */
    public UserAccessTokenRecord() {
        super(UserAccessToken.USER_ACCESS_TOKEN);
    }

    /**
     * Create a detached, initialised UserAccessTokenRecord
     */
    public UserAccessTokenRecord(String userId, String accessToken, String refreshToken, Timestamp expiredAt) {
        super(UserAccessToken.USER_ACCESS_TOKEN);

        set(0, userId);
        set(1, accessToken);
        set(2, refreshToken);
        set(3, expiredAt);
    }
}
