/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.UserAccessToken;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccessTokenRecord extends UpdatableRecordImpl<UserAccessTokenRecord> implements Record5<String, String, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = -368149617;

    /**
     * Setter for <code>public.user_access_token.user_id</code>.
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_access_token.user_id</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_access_token.access_token</code>.
     */
    public void setAccessToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_access_token.access_token</code>.
     */
    public String getAccessToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_access_token.refresh_token</code>.
     */
    public void setRefreshToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_access_token.refresh_token</code>.
     */
    public String getRefreshToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_access_token.expired_at</code>.
     */
    public void setExpiredAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_access_token.expired_at</code>.
     */
    public OffsetDateTime getExpiredAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.user_access_token.refresh_expired_at</code>.
     */
    public void setRefreshExpiredAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_access_token.refresh_expired_at</code>.
     */
    public OffsetDateTime getRefreshExpiredAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserAccessToken.USER_ACCESS_TOKEN.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return UserAccessToken.USER_ACCESS_TOKEN.ACCESS_TOKEN;
    }

    @Override
    public Field<String> field3() {
        return UserAccessToken.USER_ACCESS_TOKEN.REFRESH_TOKEN;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return UserAccessToken.USER_ACCESS_TOKEN.EXPIRED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return UserAccessToken.USER_ACCESS_TOKEN.REFRESH_EXPIRED_AT;
    }

    @Override
    public String component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getAccessToken();
    }

    @Override
    public String component3() {
        return getRefreshToken();
    }

    @Override
    public OffsetDateTime component4() {
        return getExpiredAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getRefreshExpiredAt();
    }

    @Override
    public String value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getAccessToken();
    }

    @Override
    public String value3() {
        return getRefreshToken();
    }

    @Override
    public OffsetDateTime value4() {
        return getExpiredAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getRefreshExpiredAt();
    }

    @Override
    public UserAccessTokenRecord value1(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserAccessTokenRecord value2(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public UserAccessTokenRecord value3(String value) {
        setRefreshToken(value);
        return this;
    }

    @Override
    public UserAccessTokenRecord value4(OffsetDateTime value) {
        setExpiredAt(value);
        return this;
    }

    @Override
    public UserAccessTokenRecord value5(OffsetDateTime value) {
        setRefreshExpiredAt(value);
        return this;
    }

    @Override
    public UserAccessTokenRecord values(String value1, String value2, String value3, OffsetDateTime value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccessTokenRecord
     */
    public UserAccessTokenRecord() {
        super(UserAccessToken.USER_ACCESS_TOKEN);
    }

    /**
     * Create a detached, initialised UserAccessTokenRecord
     */
    public UserAccessTokenRecord(String userId, String accessToken, String refreshToken, OffsetDateTime expiredAt, OffsetDateTime refreshExpiredAt) {
        super(UserAccessToken.USER_ACCESS_TOKEN);

        set(0, userId);
        set(1, accessToken);
        set(2, refreshToken);
        set(3, expiredAt);
        set(4, refreshExpiredAt);
    }
}
