/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables.records;


import com.plumealerts.api.db.tables.UserLoginRequest;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLoginRequestRecord extends UpdatableRecordImpl<UserLoginRequestRecord> implements Record3<String, Timestamp, String> {

    private static final long serialVersionUID = 1049336381;

    /**
     * Setter for <code>public.user_login_request.state</code>.
     */
    public void setState(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_login_request.state</code>.
     */
    public String getState() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_login_request.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_login_request.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.user_login_request.scopes</code>.
     */
    public void setScopes(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_login_request.scopes</code>.
     */
    public String getScopes() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Timestamp> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserLoginRequest.USER_LOGIN_REQUEST.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return UserLoginRequest.USER_LOGIN_REQUEST.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserLoginRequest.USER_LOGIN_REQUEST.SCOPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getScopes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getScopes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLoginRequestRecord value1(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLoginRequestRecord value2(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLoginRequestRecord value3(String value) {
        setScopes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLoginRequestRecord values(String value1, Timestamp value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserLoginRequestRecord
     */
    public UserLoginRequestRecord() {
        super(UserLoginRequest.USER_LOGIN_REQUEST);
    }

    /**
     * Create a detached, initialised UserLoginRequestRecord
     */
    public UserLoginRequestRecord(String state, Timestamp createdAt, String scopes) {
        super(UserLoginRequest.USER_LOGIN_REQUEST);

        set(0, state);
        set(1, createdAt);
        set(2, scopes);
    }
}
