/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db.tables;


import com.plumealerts.api.db.Indexes;
import com.plumealerts.api.db.Keys;
import com.plumealerts.api.db.Public;
import com.plumealerts.api.db.tables.records.DashboardRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Dashboard extends TableImpl<DashboardRecord> {

    private static final long serialVersionUID = -2073486114;

    /**
     * The reference instance of <code>public.dashboard</code>
     */
    public static final Dashboard DASHBOARD = new Dashboard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DashboardRecord> getRecordType() {
        return DashboardRecord.class;
    }

    /**
     * The column <code>public.dashboard.channel_id</code>.
     */
    public final TableField<DashboardRecord, String> CHANNEL_ID = createField(DSL.name("channel_id"), org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.dashboard.user_id</code>.
     */
    public final TableField<DashboardRecord, String> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.dashboard.type</code>.
     */
    public final TableField<DashboardRecord, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.dashboard.x</code>.
     */
    public final TableField<DashboardRecord, Short> X = createField(DSL.name("x"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.dashboard.y</code>.
     */
    public final TableField<DashboardRecord, Short> Y = createField(DSL.name("y"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.dashboard.width</code>.
     */
    public final TableField<DashboardRecord, Short> WIDTH = createField(DSL.name("width"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.dashboard.height</code>.
     */
    public final TableField<DashboardRecord, Short> HEIGHT = createField(DSL.name("height"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.dashboard.show</code>.
     */
    public final TableField<DashboardRecord, Boolean> SHOW = createField(DSL.name("show"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.dashboard</code> table reference
     */
    public Dashboard() {
        this(DSL.name("dashboard"), null);
    }

    /**
     * Create an aliased <code>public.dashboard</code> table reference
     */
    public Dashboard(String alias) {
        this(DSL.name(alias), DASHBOARD);
    }

    /**
     * Create an aliased <code>public.dashboard</code> table reference
     */
    public Dashboard(Name alias) {
        this(alias, DASHBOARD);
    }

    private Dashboard(Name alias, Table<DashboardRecord> aliased) {
        this(alias, aliased, null);
    }

    private Dashboard(Name alias, Table<DashboardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Dashboard(Table<O> child, ForeignKey<O, DashboardRecord> key) {
        super(child, key, DASHBOARD);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DASHBOARD_PKEY1);
    }

    @Override
    public UniqueKey<DashboardRecord> getPrimaryKey() {
        return Keys.DASHBOARD_PKEY1;
    }

    @Override
    public List<UniqueKey<DashboardRecord>> getKeys() {
        return Arrays.<UniqueKey<DashboardRecord>>asList(Keys.DASHBOARD_PKEY1);
    }

    @Override
    public List<ForeignKey<DashboardRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DashboardRecord, ?>>asList(Keys.DASHBOARD__DASHBOARD_CHANNEL_ID_FKEY, Keys.DASHBOARD__DASHBOARD_USER_ID_FKEY1);
    }

    public Users dashboard_DashboardChannelIdFkey() {
        return new Users(this, Keys.DASHBOARD__DASHBOARD_CHANNEL_ID_FKEY);
    }

    public Users dashboard_DashboardUserIdFkey1() {
        return new Users(this, Keys.DASHBOARD__DASHBOARD_USER_ID_FKEY1);
    }

    @Override
    public Dashboard as(String alias) {
        return new Dashboard(DSL.name(alias), this);
    }

    @Override
    public Dashboard as(Name alias) {
        return new Dashboard(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dashboard rename(String name) {
        return new Dashboard(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dashboard rename(Name name) {
        return new Dashboard(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, Short, Short, Short, Short, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
