DROP TABLE twitch_followers;
DROP TABLE twitch_bits;
DROP TABLE twitch_subscriptions;
DROP TABLE twitch_subscriptions_gift;

CREATE TABLE notification
(
    ID         BIGINT GENERATED ALWAYS AS IDENTITY,

    CHANNEL_ID VARCHAR(36) NOT NULL,
    USER_ID    VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    HIDE       BOOLEAN DEFAULT FALSE,

    TYPE       TEXT        NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (CHANNEL_ID) references users (ID)
);

CREATE TABLE twitch_followers
(
    NOTIFICATION_ID   BIGINT      NOT NULL,

    FOLLOWER_USERNAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID),
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES notification (ID)
);

CREATE TABLE twitch_bits
(
    NOTIFICATION_ID  BIGINT  NOT NULL,
    MESSAGE_ID       VARCHAR(36),

    ANONYMOUS        BOOLEAN NOT NULL,
    MESSAGE          TEXT,
    MESSAGE_USERNAME VARCHAR(25),
    BITS_USED        INT     NOT NULL,
    TOTAL_BITS       INT     NOT NULL,

    PRIMARY KEY (NOTIFICATION_ID),
    UNIQUE (MESSAGE_ID),
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES notification (ID)
);

CREATE TABLE twitch_subscriptions
(
    NOTIFICATION_ID        BIGINT      NOT NULL,

    RECIPIENT_USERNAME     VARCHAR(25) NOT NULL,
    RECIPIENT_DISPLAY_NAME VARCHAR(36) NOT NULL,

    SUB_PLAN               TEXT        NOT NULL,
    CUMULATIVE_MONTHS      INT         NOT NULL,
    STREAK_MONTHS          INT         NOT NULL,
    CONTEXT                TEXT        NOT NULL,
    MESSAGE                TEXT,

    PRIMARY KEY (NOTIFICATION_ID),
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES notification (ID)
);

CREATE TABLE twitch_subscriptions_gift
(
    NOTIFICATION_ID     BIGINT      NOT NULL,
    RECIPIENT_USERNAME  VARCHAR(25) NOT NULL,
    SUB_PLAN            TEXT        NOT NULL,
    ANONYMOUS           BOOLEAN     NOT NULL,

    GIFTER_ID           VARCHAR(36),
    GIFTER_USERNAME     VARCHAR(25),
    GIFTER_DISPLAY_NAME VARCHAR(36),

    PRIMARY KEY (NOTIFICATION_ID),
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES notification (ID)
);