CREATE TABLE dashboard
(
    USER_ID VARCHAR(36),
    TYPE    TEXT,

    X       SMALLINT NOT NULL DEFAULT 0,
    Y       SMALLINT NOT NULL DEFAULT 0,
    WIDTH   SMALLINT NOT NULL DEFAULT 0,
    HEIGHT  SMALLINT NOT NULL DEFAULT 0,
    SHOW    BOOL     NOT NULL DEFAULT TRUE,

    PRIMARY KEY (USER_ID, TYPE),
    FOREIGN KEY (USER_ID) REFERENCES users (ID)
);