/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db;


import com.plumealerts.api.db.tables.Scopes;
import com.plumealerts.api.db.tables.UserAccessToken;
import com.plumealerts.api.db.tables.UserLoginRequest;
import com.plumealerts.api.db.tables.Users;
import com.plumealerts.api.db.tables.records.ScopesRecord;
import com.plumealerts.api.db.tables.records.UserAccessTokenRecord;
import com.plumealerts.api.db.tables.records.UserLoginRequestRecord;
import com.plumealerts.api.db.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ScopesRecord> SCOPES_PKEY = UniqueKeys0.SCOPES_PKEY;
    public static final UniqueKey<UserAccessTokenRecord> USER_ACCESS_TOKEN_PKEY = UniqueKeys0.USER_ACCESS_TOKEN_PKEY;
    public static final UniqueKey<UserLoginRequestRecord> USER_LOGIN_REQUEST_PKEY = UniqueKeys0.USER_LOGIN_REQUEST_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserAccessTokenRecord, UsersRecord> USER_ACCESS_TOKEN__USER_ACCESS_TOKEN_USER_ID_FKEY = ForeignKeys0.USER_ACCESS_TOKEN__USER_ACCESS_TOKEN_USER_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ScopesRecord> SCOPES_PKEY = Internal.createUniqueKey(Scopes.SCOPES, "scopes_pkey", Scopes.SCOPES.SCOPE);
        public static final UniqueKey<UserAccessTokenRecord> USER_ACCESS_TOKEN_PKEY = Internal.createUniqueKey(UserAccessToken.USER_ACCESS_TOKEN, "user_access_token_pkey", UserAccessToken.USER_ACCESS_TOKEN.USER_ID);
        public static final UniqueKey<UserLoginRequestRecord> USER_LOGIN_REQUEST_PKEY = Internal.createUniqueKey(UserLoginRequest.USER_LOGIN_REQUEST, "user_login_request_pkey", UserLoginRequest.USER_LOGIN_REQUEST.STATE, UserLoginRequest.USER_LOGIN_REQUEST.CREATED_AT);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserAccessTokenRecord, UsersRecord> USER_ACCESS_TOKEN__USER_ACCESS_TOKEN_USER_ID_FKEY = Internal.createForeignKey(com.plumealerts.api.db.Keys.USERS_PKEY, UserAccessToken.USER_ACCESS_TOKEN, "user_access_token__user_access_token_user_id_fkey", UserAccessToken.USER_ACCESS_TOKEN.USER_ID);
    }
}
