/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db;


import com.plumealerts.api.db.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1116310787;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.dashboard</code>.
     */
    public final Dashboard DASHBOARD = com.plumealerts.api.db.tables.Dashboard.DASHBOARD;

    /**
     * The table <code>public.notification</code>.
     */
    public final Notification NOTIFICATION = com.plumealerts.api.db.tables.Notification.NOTIFICATION;

    /**
     * The table <code>public.scopes</code>.
     */
    public final Scopes SCOPES = com.plumealerts.api.db.tables.Scopes.SCOPES;

    /**
     * The table <code>public.twitch_bits</code>.
     */
    public final TwitchBits TWITCH_BITS = com.plumealerts.api.db.tables.TwitchBits.TWITCH_BITS;

    /**
     * The table <code>public.twitch_followers</code>.
     */
    public final TwitchFollowers TWITCH_FOLLOWERS = com.plumealerts.api.db.tables.TwitchFollowers.TWITCH_FOLLOWERS;

    /**
     * The table <code>public.twitch_subscriptions</code>.
     */
    public final TwitchSubscriptions TWITCH_SUBSCRIPTIONS = com.plumealerts.api.db.tables.TwitchSubscriptions.TWITCH_SUBSCRIPTIONS;

    /**
     * The table <code>public.twitch_subscriptions_gift</code>.
     */
    public final TwitchSubscriptionsGift TWITCH_SUBSCRIPTIONS_GIFT = com.plumealerts.api.db.tables.TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT;

    /**
     * The table <code>public.twitch_user_access_token</code>.
     */
    public final TwitchUserAccessToken TWITCH_USER_ACCESS_TOKEN = com.plumealerts.api.db.tables.TwitchUserAccessToken.TWITCH_USER_ACCESS_TOKEN;

    /**
     * The table <code>public.user_login_request</code>.
     */
    public final UserLoginRequest USER_LOGIN_REQUEST = com.plumealerts.api.db.tables.UserLoginRequest.USER_LOGIN_REQUEST;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.plumealerts.api.db.tables.Users.USERS;

    /**
     * The table <code>public.users_pubsub</code>.
     */
    public final UsersPubsub USERS_PUBSUB = com.plumealerts.api.db.tables.UsersPubsub.USERS_PUBSUB;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Dashboard.DASHBOARD,
                Notification.NOTIFICATION,
                Scopes.SCOPES,
                TwitchBits.TWITCH_BITS,
                TwitchFollowers.TWITCH_FOLLOWERS,
                TwitchSubscriptions.TWITCH_SUBSCRIPTIONS,
                TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT,
                TwitchUserAccessToken.TWITCH_USER_ACCESS_TOKEN,
                UserLoginRequest.USER_LOGIN_REQUEST,
                Users.USERS,
                UsersPubsub.USERS_PUBSUB);
    }
}
