/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db;


import com.plumealerts.api.db.tables.Scopes;
import com.plumealerts.api.db.tables.UserAccessToken;
import com.plumealerts.api.db.tables.UserLoginRequest;
import com.plumealerts.api.db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1787439494;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.scopes</code>.
     */
    public final Scopes SCOPES = com.plumealerts.api.db.tables.Scopes.SCOPES;

    /**
     * The table <code>public.user_access_token</code>.
     */
    public final UserAccessToken USER_ACCESS_TOKEN = com.plumealerts.api.db.tables.UserAccessToken.USER_ACCESS_TOKEN;

    /**
     * The table <code>public.user_login_request</code>.
     */
    public final UserLoginRequest USER_LOGIN_REQUEST = com.plumealerts.api.db.tables.UserLoginRequest.USER_LOGIN_REQUEST;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.plumealerts.api.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Scopes.SCOPES,
            UserAccessToken.USER_ACCESS_TOKEN,
            UserLoginRequest.USER_LOGIN_REQUEST,
            Users.USERS);
    }
}
