/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.api.db;


import com.plumealerts.api.db.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.notification</code>.
     */
    public static final Notification NOTIFICATION = Notification.NOTIFICATION;

    /**
     * The table <code>public.scopes</code>.
     */
    public static final Scopes SCOPES = Scopes.SCOPES;

    /**
     * The table <code>public.twitch_bits</code>.
     */
    public static final TwitchBits TWITCH_BITS = TwitchBits.TWITCH_BITS;

    /**
     * The table <code>public.twitch_followers</code>.
     */
    public static final TwitchFollowers TWITCH_FOLLOWERS = TwitchFollowers.TWITCH_FOLLOWERS;

    /**
     * The table <code>public.twitch_subscriptions</code>.
     */
    public static final TwitchSubscriptions TWITCH_SUBSCRIPTIONS = TwitchSubscriptions.TWITCH_SUBSCRIPTIONS;

    /**
     * The table <code>public.twitch_subscriptions_gift</code>.
     */
    public static final TwitchSubscriptionsGift TWITCH_SUBSCRIPTIONS_GIFT = TwitchSubscriptionsGift.TWITCH_SUBSCRIPTIONS_GIFT;

    /**
     * The table <code>public.twitch_user_access_token</code>.
     */
    public static final TwitchUserAccessToken TWITCH_USER_ACCESS_TOKEN = TwitchUserAccessToken.TWITCH_USER_ACCESS_TOKEN;

    /**
     * The table <code>public.user_access_token</code>.
     */
    public static final UserAccessToken USER_ACCESS_TOKEN = UserAccessToken.USER_ACCESS_TOKEN;

    /**
     * The table <code>public.user_login_request</code>.
     */
    public static final UserLoginRequest USER_LOGIN_REQUEST = UserLoginRequest.USER_LOGIN_REQUEST;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.users_pubsub</code>.
     */
    public static final UsersPubsub USERS_PUBSUB = UsersPubsub.USERS_PUBSUB;
}
